name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - uses: danie1net0-labs/hello-world-github-actions@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-world-image:$(date +%s)
